name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Zip Folder
        run: zip -r ${{ github.event.repository.name }}_${{ github.ref }}.zip . -x ".git/*" ".github/*" ".gitignore"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref }}
          files: ${{ github.event.repository.name }}_${{ github.ref }}.zip
          generate_release_notes: true